databases:
  - name: dpg-colvss21hbls7398563g-a
    plan: free
    databaseName: user_management_xn9a
    user: root

services:
  - type: web
    plan: free
    name: ecommerce
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn ecommerce.asgi:application -k uvicorn.workers.UvicornWorker"  
      envVars:
      - key: 'postgres://root:GFiRzrWmzwKQN7S9nBbMOeeol2Hv3tqW@dpg-colvss21hbls7398563g-a/user_management_xn9a'
        fromDatabase:
          name: user_management_xn9a
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4