databases:
  - name: verceldb
    plan: free
    databaseName: verceldb
    user: default

services:
  - type: web
    plan: free
    name: ecommerce
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn ecommerce.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: verceldb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "4"
