# Generated by Django 4.2.13 on 2024-05-22 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_product_category_alter_category_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chekout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_price', to='base.product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_name', to='base.product')),
                ('quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_quantity', to='base.cart')),
                ('total_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_total_price', to='base.cart')),
            ],
        ),
    ]
