# Generated by Django 4.2.13 on 2024-05-24 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_chekout_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='products',
        ),
    ]
